window.model = {
  data: {
    // todoList: [
    //   {
    //     id: 1624169471206,
    //     mes: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam maiores dolor quo perspiciatis est vero, dolorem, vel eligendi dolorum incidunt obcaecati id numquam odio ab aliquam repudiandae quaerat culpa inventore?",
    //     completed: false,
    //     tasksetId: 123,
    //     hide: false,
    //     due: new Date(),
    //   },
    //   {
    //     id: 1624669470206,
    //     mes: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam maiores dolor quo perspiciatis est vero, dolorem, vel eligendi dolorum incidunt obcaecati id numquam odio ab aliquam repudiandae quaerat culpa inventore?",
    //     completed: false,
    //     tasksetId: 123,
    //     hide: false,
    //     due: new Date(1627093286031),
    //   },
    //   {
    //     id: 1624169450206,
    //     mes: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam maiores dolor quo perspiciatis est vero, dolorem, vel eligendi dolorum incidunt obcaecati id numquam odio ab aliquam repudiandae quaerat culpa inventore?",
    //     completed: false,
    //     tasksetId: 124,
    //     hide: false,
    //     due: new Date(),
    //   },
    //   {
    //     id: 2624166470206,
    //     mes: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam maiores dolor quo perspiciatis est vero, dolorem, vel eligendi dolorum incidunt obcaecati id numquam odio ab aliquam repudiandae quaerat culpa inventore?",
    //     completed: false,
    //     tasksetId: 124,
    //     hide: false,
    //     due: new Date(1627093286031),
    //   },
    //   {
    //     id: 1524169470206,
    //     mes: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam maiores dolor quo perspiciatis est vero, dolorem, vel eligendi dolorum incidunt obcaecati id numquam odio ab aliquam repudiandae quaerat culpa inventore?",
    //     completed: false,
    //     tasksetId: 125,
    //     hide: false,
    //     due: new Date(),
    //   },
    //   {
    //     id: 1627169470206,
    //     mes: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam maiores dolor quo perspiciatis est vero, dolorem, vel eligendi dolorum incidunt obcaecati id numquam odio ab aliquam repudiandae quaerat culpa inventore?",
    //     completed: false,
    //     tasksetId: 125,
    //     hide: false,
    //     due: new Date(1627093286031),
    //   },
    // ],
    taskset: [
      {
        id: 1,
        name: "todo-list1",
        active: true,
        todoList: [
          {
            id: 1624169471206,
            mes: "k ipsum dolor sit amet consectetur adipisicing elit. Aperiam maiores dolor quo perspiciatis est vero, dolorem, vel eligendi dolorum incidunt obcaecati id numquam odio ab aliquam repudiandae quaerat culpa inventore?",
            completed: false,
            tasksetId: 123,
            hide: false,
            due: new Date(),
          },
          {
            id: 1624669470206,
            mes: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam maiores dolor quo perspiciatis est vero, dolorem, vel eligendi dolorum incidunt obcaecati id numquam odio ab aliquam repudiandae quaerat culpa inventore?",
            completed: false,
            tasksetId: 123,
            hide: false,
            due: new Date(1627093286031),
          },
        ],
      },
      {
        id: 2,
        name: "todo-list2",
        active: false,
        todoList: [
          {
            id: 1624169450206,
            mes: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam maiores dolor quo perspiciatis est vero, dolorem, vel eligendi dolorum incidunt obcaecati id numquam odio ab aliquam repudiandae quaerat culpa inventore?",
            completed: false,
            tasksetId: 124,
            hide: false,
            due: new Date(),
          },
          {
            id: 2624166470206,
            mes: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam maiores dolor quo perspiciatis est vero, dolorem, vel eligendi dolorum incidunt obcaecati id numquam odio ab aliquam repudiandae quaerat culpa inventore?",
            completed: false,
            tasksetId: 124,
            hide: false,
            due: new Date(1627093286031),
          },
        ],
      },
      {
        id: 3,
        name: "todo-list3",
        active: false,
        todoList: [
          {
            id: 1524169470206,
            mes: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam maiores dolor quo perspiciatis est vero, dolorem, vel eligendi dolorum incidunt obcaecati id numquam odio ab aliquam repudiandae quaerat culpa inventore?",
            completed: false,
            tasksetId: 125,
            hide: false,
            due: new Date(),
          },
          {
            id: 1627169470206,
            mes: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam maiores dolor quo perspiciatis est vero, dolorem, vel eligendi dolorum incidunt obcaecati id numquam odio ab aliquam repudiandae quaerat culpa inventore?",
            completed: false,
            tasksetId: 125,
            hide: false,
            due: new Date(1627093286031),
          },
        ],
      },
    ],
    filter: "left", // left , done. total
    inputMes: "",
  },
};
